version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jiji-crawler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-z7i4yhla5tyl"
s3_prefix = "jiji-crawler"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
